name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arm64:
    uses: ./.github/workflows/build-image.yml
    with:
      platform: linux/arm64

  build-amd64:
    uses: ./.github/workflows/build-image.yml
    with:
      platform: linux/amd64
